<a href="https://colab.research.google.com/github/Shubhro97/Shubhro-Day-2-Assignment-Python-for-Data-Science/blob/main/Shubhro_Day_2_Assignment_Python_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [4,5,6,7,8]

arr1 = np.array([lst1, lst2, lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [3]:
arr1[1:,1:3]

array([[3, 4],
       [5, 6]])

In [5]:
arr1[1,1:4]

array([3, 4, 5])